// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7XWI6eYl0LkomyBgwBZzbLEeG-lpfIOs',
    appId: '1:1010122754215:web:4f4ac667c83ddb17833382',
    messagingSenderId: '1010122754215',
    projectId: 'mawqif-76bad',
    authDomain: 'mawqif-76bad.firebaseapp.com',
    storageBucket: 'mawqif-76bad.firebasestorage.app',
    measurementId: 'G-6STF916XEE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEVbVxsRwAiN-LNgL0CgKUFGnUUUHqO1U',
    appId: '1:1010122754215:android:9b4b5136a16fa065833382',
    messagingSenderId: '1010122754215',
    projectId: 'mawqif-76bad',
    storageBucket: 'mawqif-76bad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnYGVvB3EAXpoC6WhC01jX1A9fWYefRgk',
    appId: '1:1010122754215:ios:b04920788f5b68f2833382',
    messagingSenderId: '1010122754215',
    projectId: 'mawqif-76bad',
    storageBucket: 'mawqif-76bad.firebasestorage.app',
    iosBundleId: 'mawqif.com.mawqif1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnYGVvB3EAXpoC6WhC01jX1A9fWYefRgk',
    appId: '1:1010122754215:ios:b04920788f5b68f2833382',
    messagingSenderId: '1010122754215',
    projectId: 'mawqif-76bad',
    storageBucket: 'mawqif-76bad.firebasestorage.app',
    iosBundleId: 'mawqif.com.mawqif1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7XWI6eYl0LkomyBgwBZzbLEeG-lpfIOs',
    appId: '1:1010122754215:web:9daf286d2655daa4833382',
    messagingSenderId: '1010122754215',
    projectId: 'mawqif-76bad',
    authDomain: 'mawqif-76bad.firebaseapp.com',
    storageBucket: 'mawqif-76bad.firebasestorage.app',
    measurementId: 'G-9TH4R8RVQJ',
  );
}
